name: "Complete Chapter 1 Quiz"
description: Learn web fundamentals and complete the quiz
title: "Complete Chapter 1 Quiz"
labels: ["quiz", "chapter1-task"]
body:
  - type: markdown
    attributes:
      value: |
        ## Chapter 1 Quiz
        In this task, you'll learn about web fundamentals and complete a quiz to test your understanding.
  
  - type: markdown
    attributes:
      value: |        ### Instructions
        1. Read through the content in `docs/Chapter1.md` to understand the course workflow and web fundamentals.
        2. Open the quiz in `docs/Chapter1-Quiz.md` and answer all 5 questions.
        3. For each question, place an 'X' in the brackets [ ] next to your chosen answer:
           ```
           [ ] A. First option
           [X] B. Second option (this is your selected answer)
           [ ] C. Third option
           [ ] D. Fourth option
           ```
        4. Commit your changes to complete the quiz.
        5. This issue will be **automatically closed** when you successfully complete the quiz with correct answers.
  
  - type: checkboxes
    id: tasks
    attributes:
      label: Checklist
      description: Please complete all the tasks below
      options:
        - label: Read the Chapter 1 content in docs/Chapter1.md
          required: true
        - label: Answer all 5 quiz questions in docs/Chapter1-Quiz.md
          required: true
        - label: Commit changes to the quiz file
          required: true
