name: Chapter 1 - Web Fundamentals

on:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - 'resources/Quiz1.md'
  workflow_dispatch:
  repository_dispatch:
    types: [check-chapter1]

permissions:
  contents: write
  issues: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      should_run: ${{ steps.check_step.outputs.should_run }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
      - id: check_step
        run: |
          CURRENT_STEP=$(cat ./.github/steps/-step.txt)
          if [ "$CURRENT_STEP" == "1" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
            echo "Current step is $CURRENT_STEP, skipping Chapter 1 workflow."

  create_issues:
    needs: get_current_step
    if: >
      !github.event.repository.is_template &&
      needs.get_current_step.outputs.should_run == 'true' &&
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create Quiz Task Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: existingIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'chapter1-task,quiz',
              state: 'open'
            });
            
            if (existingIssues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Chapter 1: Complete the Web Fundamentals Quiz',
                body: `
                # Complete the Web Fundamentals Quiz
                
                1. Navigate to the \`resources/Quiz1.md\` file
                2. Answer all questions by marking the correct answers with [X]
                3. Select exactly 3 answers total (one for each question)
                4. Commit your changes to complete this task
                
                This issue will automatically close when you successfully complete the quiz.
                `,
                labels: ['chapter1-task', 'quiz']
              });
            }

  validate_quiz:
    name: Validate Quiz Answers
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if quiz file exists
        run: |
          if [ ! -f "resources/Quiz1.md" ]; then
            echo "::error::resources/Quiz1.md is missing"
            exit 1
          fi

      - name: Validate quiz answers
        id: quiz_validation
        run: |
          QUIZ_FILE="resources/Quiz1.md"
          SELECTED_COUNT=$(grep -c "\[X\]" "$QUIZ_FILE" || true)
          if [ "$SELECTED_COUNT" -eq 0 ]; then
            echo "::error::No answers selected. Mark answers with [X]."
            exit 1
          fi
          if [ "$SELECTED_COUNT" -ne 3 ]; then
            echo "::error::Found $SELECTED_COUNT selections; select exactly 3 answers (one for each question)."
            exit 1
          fi
          
          # Check if each question has exactly one answer
          Q1_COUNT=$(grep -A5 "1. \*\*What is the DOM" "$QUIZ_FILE" | grep -c "\[X\]" || true)
          Q2_COUNT=$(grep -A5 "2. \*\*Which HTTP method" "$QUIZ_FILE" | grep -c "\[X\]" || true)
          Q3_COUNT=$(grep -A5 "3. \*\*During the browser" "$QUIZ_FILE" | grep -c "\[X\]" || true)
          
          if [ "$Q1_COUNT" -ne 1 ] || [ "$Q2_COUNT" -ne 1 ] || [ "$Q3_COUNT" -ne 1 ]; then
            echo "::error::Each question must have exactly one answer selected."
            exit 1
          fi
          
          # Check for correct answers
          INCORRECT=0
          if ! grep -A5 "1. \*\*What is the DOM" "$QUIZ_FILE" | grep -q "\[X\] B. A tree-like representation of the HTML document"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "2. \*\*Which HTTP method" "$QUIZ_FILE" | grep -q "\[X\] B. GET"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "3. \*\*During the browser" "$QUIZ_FILE" | grep -q "\[X\] C. The browser combines the DOM and CSSOM into a render tree for layout"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          
          if [ "$INCORRECT" -gt 0 ]; then
            echo "::error::Found $INCORRECT incorrect answers."
            exit 1
          fi
          echo "quiz_completed=true" >> $GITHUB_OUTPUT

      - name: Close Completed Quiz Issue
        if: steps.quiz_validation.outputs.quiz_completed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'chapter1-task,quiz',
              state: 'open'
            });
            
            for (const issue of issues) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }

      - name: Ensure All Chapter-1 Tasks Are Closed
        if: steps.quiz_validation.outputs.quiz_completed == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Add a delay function to wait between retries
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
            
            // Maximum number of retries and retry delay in ms
            const MAX_RETRIES = 3;
            const RETRY_DELAY = 3000; // 3 seconds
            
            let retries = 0;
            let openIssues = [];
            
            while (retries < MAX_RETRIES) {
              try {
                const { data: issues } = await github.rest.issues.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: 'chapter1-task',
                  state: 'open'
                });
                
                if (issues.length === 0) {
                  console.log('All chapter1-task issues are closed!');
                  return; // Success, exit the script
                }
                
                openIssues = issues;
                console.log(`Found ${issues.length} open issues. Retrying in ${RETRY_DELAY/1000} seconds... (Attempt ${retries + 1}/${MAX_RETRIES})`);
                
                // Wait before next retry
                await delay(RETRY_DELAY);
                retries++;
              } catch (error) {
                console.error(`Error checking issues: ${error.message}`);
                core.warning(`Error checking issues: ${error.message}`);
                break;
              }
            }
            
            if (openIssues.length > 0) {
              core.warning(`There are still ${openIssues.length} open chapter1-task issues. This may be due to API delay.`);
              // Log issue numbers for debugging
              openIssues.forEach(issue => console.log(`Issue #${issue.number}: ${issue.title}`));
            }

      - name: Update to step 2
        if: success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: ${{ github.ref_name }}
