name: Step 1, Web Fundamentals

on:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - 'resources/Quiz1.md'
  workflow_dispatch:
  repository_dispatch:
    types: [check-chapter1]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          current_step=$(cat ./.github/steps/-step.txt)
          echo "current_step=$current_step" >> $GITHUB_OUTPUT
          if [ "$current_step" -eq "1" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      should_run: ${{ steps.get_step.outputs.should_run }}

  validate_quiz:
    name: Validate Quiz Answers
    needs: get_current_step
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate quiz answers
        id: quiz_validation
        run: |
          QUIZ="resources/Quiz1.md"
          if [ ! -f "$QUIZ" ]; then
            echo "::error::$QUIZ is missing"
            exit 1
          fi        
          # Check for correct answers
          INCORRECT=0
          if ! grep -A5 "1. \*\*What is the DOM" "$QUIZ" | grep -q "\[X\] B. A tree-like representation of the HTML document"; then
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "2. \*\*Which HTTP method" "$QUIZ" | grep -q "\[X\] B. GET"; then
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "3. \*\*During the browser" "$QUIZ" | grep -q "\[X\] C. The browser combines the DOM and CSSOM into a render tree for layout"; then
            INCORRECT=$((INCORRECT+1))
          fi
          if [ "$INCORRECT" -gt 0 ]; then
            echo "::error::Found $INCORRECT incorrect answers."
            exit 1
          fi
          echo "quiz_ok=true" >> $GITHUB_OUTPUT

      - name: Update to step 2
        if: steps.quiz_validation.outputs.quiz_ok == 'true' && success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
          branch_name: ${{ github.ref_name }}
