name: Step 12, APIs and Hosting

on:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - 'resources/Quiz12.md'
      - 'src/components/Contact.tsx'
      - 'src/api/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
  repository_dispatch:
    types: [check-chapter12]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          current_step=$(cat ./.github/steps/-step.txt)
          echo "current_step=$current_step" >> $GITHUB_OUTPUT
          if [ "$current_step" -eq "12" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      should_run: ${{ steps.get_step.outputs.should_run }}

  validate_and_progress:
    name: Validate Quiz Answers and Progress
    needs: get_current_step
    if: >
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Validate quiz answers
        id: quiz_validation
        run: |
          QUIZ="resources/Quiz12.md"
          if [ ! -f "$QUIZ" ]; then
            echo "::error::$QUIZ is missing"
            exit 1
          fi
          # Check for correct answers
          INCORRECT=0
          if ! grep -A5 "1. \*\*Which library is recommended" "$QUIZ" | grep -q "\[X\] C. React Testing Library"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "2. \*\*Which function from" "$QUIZ" | grep -q "\[X\] A. render"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "3. \*\*Which Jest function" "$QUIZ" | grep -q "\[X\] A. expect()"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if [ "$INCORRECT" -gt 0 ]; then
            echo "::error::Found $INCORRECT incorrect answers."
            exit 1
          fi
          echo "quiz_ok=true" >> $GITHUB_OUTPUT

      - name: Check Contact Component and API
        id: contact_api_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          # Check Contact component
          if [ ! -f "src/components/Contact.tsx" ]; then
            echo "::error::src/components/Contact.tsx is missing"
            exit 1
          fi          
          # Check for form elements in Contact component
          if ! grep -q -E "<form|<input|<textarea|<button" "src/components/Contact.tsx"; then
            echo "::error::Contact.tsx does not contain form elements"
            exit 1
          fi          
          # Check for API handling file
          if [ ! -f "src/api/contact.ts" ]; then
            echo "::error::src/api/contact.ts is missing"
            exit 1
          fi          
          # Check for environment variable usage
          if ! grep -q "import.meta.env" "src/api/contact.ts"; then
            echo "::error::src/api/contact.ts does not use environment variables"
            exit 1
          fi          
          echo "contact_api_ok=true" >> $GITHUB_OUTPUT

      - name: Check Deployment Workflow
        id: deployment_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true' && steps.contact_api_check.outputs.contact_api_ok == 'true'
        run: |
          # Check for deployment workflow file
          if [ ! -f ".github/workflows/deploy.yml" ]; then
            echo "::error::.github/workflows/deploy.yml is missing"
            exit 1
          fi          
          # Check for GitHub Pages configuration in deploy workflow
          if ! grep -q -E "gh-pages|github-pages" ".github/workflows/deploy.yml"; then
            echo "::error::deploy.yml does not configure GitHub Pages"
            exit 1
          fi          
          # Check for build step in workflow
          if ! grep -q "npm run build" ".github/workflows/deploy.yml"; then
            echo "::error::deploy.yml does not include a build step"
            exit 1
          fi          
          echo "deployment_ok=true" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: npm install

      - name: Build Project
        id: build_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true' && steps.deployment_check.outputs.deployment_ok == 'true'
        run: |
          # Create a temporary .env file with placeholder values
          echo "# Temporary env file for build" > .env
          grep "VITE_" ".env.example" | sed 's/=.*/=placeholder/' >> .env
          if npm run build; then
            echo "build_ok=true" >> $GITHUB_OUTPUT
          else
            echo "::error::Build failed. Please fix the issues."
            exit 1
          fi
          # Remove temporary .env file
          rm .env

      - name: Update to Final Step
        if: >
          steps.quiz_validation.outputs.quiz_ok == 'true' &&
          steps.contact_api_check.outputs.contact_api_ok == 'true' &&
          steps.deployment_check.outputs.deployment_ok == 'true' &&
          steps.build_check.outputs.build_ok == 'true' &&
          success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 12
          to_step: 13
          branch_name: ${{ github.ref_name }}
