name: Step 2, Planning & Requirements

on:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - 'resources/Quiz2.md'
      - 'resources/SRS.md'
  workflow_dispatch:
  repository_dispatch:
    types: [check-chapter2]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          current_step=$(cat ./.github/steps/-step.txt)
          echo "current_step=$current_step" >> $GITHUB_OUTPUT
          if [ "$current_step" -eq "2" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      should_run: ${{ steps.get_step.outputs.should_run }}

  validate_and_progress:
    name: Validate Quiz Answers and Progress
    needs: get_current_step
    if: >
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate quiz answers
        id: quiz_validation
        run: |
          QUIZ="resources/Quiz2.md"
          if [ ! -f "$QUIZ" ]; then
            echo "::error::$QUIZ is missing"
            exit 1
          fi        
          # Check for correct answers
          INCORRECT=0
          if ! grep -A5 "1. \*\*Which SDLC model" "$QUIZ" | grep -q "\[X\] B. Waterfall"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "2. \*\*What is a user persona" "$QUIZ" | grep -q "\[X\] B. A fictional representation of a target user to guide design decisions"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "3. \*\*Which section of the Software" "$QUIZ" | grep -q "\[X\] B. Overall Description"; then 
            INCORRECT=$((INCORRECT+1))
          fi          
          if [ "$INCORRECT" -gt 0 ]; then
            echo "::error::Found $INCORRECT incorrect answers."
            exit 1
          fi
          echo "quiz_ok=true" >> $GITHUB_OUTPUT

      - name: Check SRS Document
        id: srs
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          if [ ! -f "resources/SRS.md" ]; then
            echo "::error::SRS document is missing. Please create resources/SRS.md"
            exit 1
          fi          
          # Check if SRS document has minimum content
          SRS_SIZE=$(wc -c < "resources/SRS.md" || echo 0)
          if [ "$SRS_SIZE" -lt 500 ]; then
            echo "::error::SRS document is too short. Please complete the document."
            exit 1
          fi
          echo "srs_ok=true" >> $GITHUB_OUTPUT

      - name: Update to Step 3
        if: steps.quiz_validation.outputs.quiz_ok == 'true' && steps.srs.outputs.srs_ok == 'true' && success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
          branch_name: ${{ github.ref_name }}
