name: Chapter 3 - Project Setup, Linting & Vite

on:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - 'resources/Quiz3.md'
      - 'vite.config.ts'
      - 'tsconfig.json'
      - 'tsconfig.app.json'
      - 'tsconfig.node.json'
      - 'package.json'
      - '.prettierrc'
      - 'eslint.config.js'
      - 'src/**'
      - 'index.html'
  workflow_dispatch:

permissions:
  contents: write
  issues: write

jobs:
  get_current_step:
    runs-on: ubuntu-latest
    outputs:
      current_step: ${{ steps.read_step.outputs.current_step }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: read_step
        run: echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
      - name: Early terminate if not on step 3
        if: steps.read_step.outputs.current_step != '3'
        run: exit 78

  create_issues:
    needs: get_current_step
    if: >
      !github.event.repository.is_template &&
      needs.get_current_step.outputs.current_step == '3' &&
      github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create Quiz Task Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: existingIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'chapter3-task,quiz',
              state: 'open'
            });
            
            if (existingIssues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Chapter 3: Complete the Project Setup Quiz',
                body: `
                # Complete the Project Setup, Linting & Vite Quiz
                
                1. Navigate to the \`resources/Quiz3.md\` file
                2. Answer all questions by marking the correct answers with [X]
                3. Select exactly 3 answers total (one for each question)
                4. Commit your changes to complete this task
                
                This issue will automatically close when you successfully complete the quiz.
                `,
                labels: ['chapter3-task', 'quiz']
              });
            }
            
      - name: Create Project Setup Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: existingIssues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'chapter3-task,project-setup',
              state: 'open'
            });
            
            if (existingIssues.length === 0) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Chapter 3: Set Up Your Vite Project',
                body: `
                # Set Up Your Vite Project
                
                1. Create a new Vite project with React and TypeScript:
                   - Use \`npm create vite@latest portfolio -- --template react-ts\`
                
                2. Set up the following files:
                   - Configure \`vite.config.ts\`
                   - Configure \`tsconfig.json\` files
                   - Configure ESLint with \`eslint.config.js\`
                   - Update \`index.html\` and base React files
                
                3. Install dependencies and verify the project structure:
                   - Run \`npm install\` to install dependencies
                   - Ensure \`src/main.tsx\` and \`src/App.tsx\` exist
                
                This issue will automatically close when you successfully complete all the required setup tasks.
                `,
                labels: ['chapter3-task', 'project-setup']
              });
            }

  validate_and_progress:
    needs: get_current_step
    if: >
      !github.event.repository.is_template &&
      needs.get_current_step.outputs.current_step == '3'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Quiz Answers
        id: quiz
        run: |
          QUIZ=resources/Quiz3.md
          COUNT=$(grep -c "\[X\]" "$QUIZ" || echo 0)
          if [ "$COUNT" -eq 0 ]; then
            echo "::error::No answers selected. Mark answers with [X]."
            exit 1
          fi
          if [ "$COUNT" -ne 3 ]; then
            echo "::error::Found $COUNT selections; select exactly 3 answers (one for each question)."
            exit 1
          fi
          
          # Check if each question has exactly one answer
          Q1_COUNT=$(grep -A5 "1. \*\*Which command scaffolds" "$QUIZ" | grep -c "\[X\]" || true)
          Q2_COUNT=$(grep -A5 "2. \*\*In the Vite project structure" "$QUIZ" | grep -c "\[X\]" || true)
          Q3_COUNT=$(grep -A5 "3. \*\*Which file configures Tailwind" "$QUIZ" | grep -c "\[X\]" || true)
          
          if [ "$Q1_COUNT" -ne 1 ] || [ "$Q2_COUNT" -ne 1 ] || [ "$Q3_COUNT" -ne 1 ]; then
            echo "::error::Each question must have exactly one answer selected."
            exit 1
          fi
          
          # Check for correct answers
          INCORRECT=0
          if ! grep -A5 "1. \*\*Which command scaffolds" "$QUIZ" | grep -q "\[X\] C. npm create vite@latest my-portfolio -- --template react-ts"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "2. \*\*In the Vite project structure" "$QUIZ" | grep -q "\[X\] C. src/main.tsx"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "3. \*\*Which file configures Tailwind" "$QUIZ" | grep -q "\[X\] B. tailwind.config.js"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          
          if [ "$INCORRECT" -gt 0 ]; then
            echo "::error::Found $INCORRECT incorrect answers."
            exit 1
          fi
          echo "quiz_ok=true" >> $GITHUB_OUTPUT

      - name: Check Vite Project Files
        id: vite_project
        if: steps.quiz.outputs.quiz_ok == 'true'
        run: |
          # Check for required Vite project files
          REQUIRED_FILES=(
            "vite.config.ts"
            "tsconfig.json"
            "package.json"
            "eslint.config.js"
            "index.html"
            "src/main.tsx"
            "src/App.tsx"
            "src/index.css"
          )
          
          MISSING_FILES=""
          for file in "${REQUIRED_FILES[@]}"; do
            if [ ! -f "$file" ]; then
              MISSING_FILES="$MISSING_FILES $file"
            fi
          done
          
          if [ ! -z "$MISSING_FILES" ]; then
            echo "::error::Missing required files:$MISSING_FILES"
            exit 1
          fi
          
          echo "vite_project_ok=true" >> $GITHUB_OUTPUT

      - name: Close Completed Quiz Issue
        if: steps.quiz.outputs.quiz_ok == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'chapter3-task,quiz',
              state: 'open'
            });
            
            for (const issue of issues) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }

      - name: Close Completed Project Setup Issue
        if: steps.vite_project.outputs.vite_project_ok == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: issues } = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: 'chapter3-task,project-setup',
              state: 'open'
            });
            
            for (const issue of issues) {
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                state: 'closed'
              });
            }

      - name: Ensure All Chapter-3 Tasks Are Closed
        if: steps.quiz.outputs.quiz_ok == 'true' && steps.vite_project.outputs.vite_project_ok == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Add a delay function to wait between retries
            const delay = ms => new Promise(resolve => setTimeout(resolve, ms));
            
            // Maximum number of retries and retry delay in ms
            const MAX_RETRIES = 3;
            const RETRY_DELAY = 3000; // 3 seconds
            
            let retries = 0;
            let openIssues = [];
            
            while (retries < MAX_RETRIES) {
              try {
                const { data: issues } = await github.rest.issues.listForRepo({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  labels: 'chapter3-task',
                  state: 'open'
                });
                
                if (issues.length === 0) {
                  console.log('All chapter3-task issues are closed!');
                  return; // Success, exit the script
                }
                
                openIssues = issues;
                console.log(`Found ${issues.length} open issues. Retrying in ${RETRY_DELAY/1000} seconds... (Attempt ${retries + 1}/${MAX_RETRIES})`);
                
                // Wait before next retry
                await delay(RETRY_DELAY);
                retries++;
              } catch (error) {
                console.error(`Error checking issues: ${error.message}`);
                core.warning(`Error checking issues: ${error.message}`);
                break;
              }
            }
            
            if (openIssues.length > 0) {
              core.warning(`There are still ${openIssues.length} open chapter3-task issues. This may be due to API delay.`);
              // Log issue numbers for debugging
              openIssues.forEach(issue => console.log(`Issue #${issue.number}: ${issue.title}`));
            }

      - name: Advance to Step 4
        if: success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
          branch_name: ${{ github.ref_name }}