name: Step 5, CSS and Tailwind

on:
  push:
    branches: [ main ]
    paths:
      - '.github/steps/-step.txt'
      - 'resources/Quiz5.md'
      - 'src/index.css'
      - 'tailwind.config.js'
      - 'package.json'
      - 'vite.config.ts'
      - 'src/App.css'
  workflow_dispatch:
  repository_dispatch:
    types: [check-chapter5]

permissions:
  contents: write

jobs:
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: get_step
        run: |
          current_step=$(cat ./.github/steps/-step.txt)
          echo "current_step=$current_step" >> $GITHUB_OUTPUT
          if [ "$current_step" -eq "5" ]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      should_run: ${{ steps.get_step.outputs.should_run }}

  validate_and_progress:
    name: Validate Quiz Answers and Progress
    needs: get_current_step
    if: >
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Validate quiz answers
        id: quiz_validation
        run: |
          QUIZ="resources/Quiz5.md"
          if [ ! -f "$QUIZ" ]; then
            echo "::error::$QUIZ is missing"
            exit 1
          fi
          # Check for correct answers
          INCORRECT=0
          if ! grep -A5 "1. \*\*Which CSS selector" "$QUIZ" | grep -q "\[X\] B. \`.container\`"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "2. \*\*What CSS property" "$QUIZ" | grep -q "\[X\] B. padding"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if ! grep -A5 "3. \*\*Which feature is used" "$QUIZ" | grep -q "\[X\] A. media queries"; then 
            INCORRECT=$((INCORRECT+1))
          fi
          if [ "$INCORRECT" -gt 0 ]; then
            echo "::error::Found $INCORRECT incorrect answers."
            exit 1
          fi
          echo "quiz_ok=true" >> $GITHUB_OUTPUT

      - name: Check Vite Config
        id: vite_config
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          if [ ! -f "vite.config.ts" ]; then
            echo "::error::vite.config.ts file is missing."
            exit 1
          fi          
          # Check for Tailwind import and plugin
          if ! grep -q "import tailwindcss from \"@tailwindcss/vite\"" "vite.config.ts"; then
            echo "::error::vite.config.ts is missing Tailwind import."
            exit 1
          fi          
          if ! grep -q "tailwindcss()" "vite.config.ts"; then
            echo "::error::vite.config.ts is missing Tailwind plugin in the plugins array."
            exit 1
          fi          
          echo "vite_config_ok=true" >> $GITHUB_OUTPUT

      - name: Check Package.json
        id: package_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          if [ ! -f "package.json" ]; then
            echo "::error::package.json file is missing."
            exit 1
          fi          
          # Check for Tailwind 4 and required packages
          PACKAGE_CHECKS=( 
            "\"tailwindcss\": \"\^4"
            "\"@tailwindcss/vite\":" 
            "\"@tailwindcss/forms\":" 
            "\"@tailwindcss/typography\":" 
          )          
          MISSING=""
          for check in "${PACKAGE_CHECKS[@]}"; do
            if ! grep -q "$check" "package.json"; then
              MISSING="$MISSING\n- $check"
            fi
          done          
          if [ ! -z "$MISSING" ]; then
            echo "::error::package.json is missing required dependencies:$MISSING"
            exit 1
          fi          
          echo "package_ok=true" >> $GITHUB_OUTPUT

      - name: Check CSS File
        id: css_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          if [ ! -f "src/index.css" ]; then
            echo "::error::src/index.css file is missing."
            exit 1
          fi          
          # Check for required CSS elements
          CSS_CHECKS=( 
            "@import \"tailwindcss\"" 
            "@layer" 
          )          
          MISSING=""
          for check in "${CSS_CHECKS[@]}"; do
            if ! grep -q "$check" "src/index.css"; then
              MISSING="$MISSING\n- $check"
            fi
          done          
          if [ ! -z "$MISSING" ]; then
            echo "::error::index.css is missing required elements:$MISSING"
            exit 1
          fi          
          echo "css_ok=true" >> $GITHUB_OUTPUT

      - name: Check App CSS File
        id: app_css_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          if [ ! -f "src/App.css" ]; then
            echo "::error::src/App.css file is missing."
            exit 1
          fi          
          # Check for required App.css elements
          APP_CSS_CHECKS=( 
            "@layer" 
            "utilities" 
          )          
          MISSING=""
          for check in "${APP_CSS_CHECKS[@]}"; do
            if ! grep -q "$check" "src/App.css"; then
              MISSING="$MISSING\n- $check"
            fi
          done          
          if [ ! -z "$MISSING" ]; then
            echo "::error::App.css is missing required elements:$MISSING"
            exit 1
          fi          
          echo "app_css_ok=true" >> $GITHUB_OUTPUT

      - name: Check Tailwind Config
        id: tailwind_check
        if: steps.quiz_validation.outputs.quiz_ok == 'true'
        run: |
          if [ ! -f "tailwind.config.js" ]; then
            echo "::error::tailwind.config.js file is missing."
            exit 1
          fi          
          # Check for required Tailwind configuration
          TAILWIND_CHECKS=( 
            "content: \[" 
            "\"./index.html\"" 
            "\"./src/\*\*/\*.{js,ts,jsx,tsx}\"" 
            "theme: {" 
            "extend: {" 
            "plugins: \[" 
          )          
          MISSING=""
          for check in "${TAILWIND_CHECKS[@]}"; do
            if ! grep -q "$check" "tailwind.config.js"; then
              MISSING="$MISSING\n- $check"
            fi
          done          
          if [ ! -z "$MISSING" ]; then
            echo "::error::tailwind.config.js is missing required configuration:$MISSING"
            exit 1
          fi
          echo "tailwind_ok=true" >> $GITHUB_OUTPUT

      - name: Update to Step 6
        if: >
          steps.quiz_validation.outputs.quiz_ok == 'true' &&
          steps.vite_config.outputs.vite_config_ok == 'true' &&
          steps.tailwind_check.outputs.tailwind_ok == 'true' &&
          steps.package_check.outputs.package_ok == 'true' &&
          steps.css_check.outputs.css_ok == 'true' &&
          steps.app_css_check.outputs.app_css_ok == 'true' &&
          success()
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 5
          to_step: 6
          branch_name: ${{ github.ref_name }}
